const BACKGROUNDS = [
  // ── Gradientes ───────────────────────────────────
  { id: 'gradiente-aurora',      label: 'Aurora',       category: 'gradient' },
  { id: 'gradiente-dusk',        label: 'Dusk',         category: 'gradient' },
  { id: 'gradiente-slate',       label: 'Slate',        category: 'gradient' },
  { id: 'gradiente-mint',        label: 'Mint',         category: 'gradient' },
  { id: 'gradiente-neon-purple', label: 'Neon',         category: 'gradient' },
  { id: 'gradiente-ocean',       label: 'Ocean',        category: 'gradient' },
  { id: 'gradiente-midnight',    label: 'Midnight',     category: 'gradient' },
  { id: 'gradiente-wine',        label: 'Wine',         category: 'gradient' },
  { id: 'gradiente-copper',      label: 'Copper',       category: 'gradient' },
  { id: 'gradiente-rose',        label: 'Rose',         category: 'gradient' },
  { id: 'gradiente-fire',        label: 'Fire',         category: 'gradient' },
  { id: 'gradiente-cosmic',      label: 'Cosmic',       category: 'gradient' },
  { id: 'gradiente-gold',        label: 'Gold',         category: 'gradient' },
  { id: 'gradiente-storm',       label: 'Storm',        category: 'gradient' },
  { id: 'gradiente-earth',       label: 'Earth',        category: 'gradient' },
  { id: 'gradiente-jungle',      label: 'Jungle',       category: 'gradient' },
  { id: 'gradiente-sunset',      label: 'Sunset',       category: 'gradient' },
  { id: 'gradiente-arctic',      label: 'Arctic',       category: 'gradient' },
  { id: 'gradiente-forest',      label: 'Forest',       category: 'gradient' },
  { id: 'gradiente-ice',         label: 'Ice',          category: 'gradient' },
  // ── Geométricos ──────────────────────────────────
  { id: 'geo-grid',              label: 'Grid',         category: 'geo' },
  { id: 'geo-dots',              label: 'Dots',         category: 'geo' },
  { id: 'geo-arcs',              label: 'Arcs',         category: 'geo' },
  { id: 'geo-diagonal',          label: 'Diagonal',     category: 'geo' },
  { id: 'geo-hexagons',          label: 'Hexágonos',    category: 'geo' },
  { id: 'geo-waves',             label: 'Ondas',        category: 'geo' },
  { id: 'geo-circles',           label: 'Círculos',     category: 'geo' },
  { id: 'geo-chevron',           label: 'Chevron',      category: 'geo' },
  { id: 'geo-radial',            label: 'Radial',       category: 'geo' },
  { id: 'geo-mesh',              label: 'Mesh',         category: 'geo' },
  { id: 'geo-plus',              label: 'Plus',         category: 'geo' },
  { id: 'geo-lines-h',           label: 'Linhas',       category: 'geo' },
  { id: 'geo-triangles',         label: 'Triângulos',   category: 'geo' },
  { id: 'geo-cross',             label: 'Cross',        category: 'geo' },
  { id: 'geo-arc-top',           label: 'Arcs Top',     category: 'geo' },
  { id: 'geo-noise-geo',         label: 'Noise Geo',    category: 'geo' },
  // ── Texturas ─────────────────────────────────────
  { id: 'texture-noise',         label: 'Noise',        category: 'texture' },
  { id: 'texture-paper',         label: 'Paper',        category: 'texture' },
  { id: 'texture-concrete',      label: 'Concrete',     category: 'texture' },
  { id: 'texture-dark-linen',    label: 'Linen',        category: 'texture' },
  { id: 'texture-marble',        label: 'Marble',       category: 'texture' },
  { id: 'texture-silk',          label: 'Silk',         category: 'texture' },
  { id: 'texture-metal',         label: 'Metal',        category: 'texture' },
  { id: 'texture-grain-dark',    label: 'Film Grain',   category: 'texture' },
  { id: 'texture-sand',          label: 'Sand',         category: 'texture' },
  { id: 'texture-fabric',        label: 'Fabric',       category: 'texture' },
  { id: 'texture-scratched',     label: 'Scratched',    category: 'texture' },
  { id: 'texture-watercolor',    label: 'Watercolor',   category: 'texture' },
  // ── Abstratos ─────────────────────────────────────
  { id: 'abstract-blob',         label: 'Blob',         category: 'abstract' },
  { id: 'abstract-flow',         label: 'Flow',         category: 'abstract' },
  { id: 'abstract-split',        label: 'Split',        category: 'abstract' },
  { id: 'abstract-spot',         label: 'Spot',         category: 'abstract' },
];
